// Generated by BulkCompiler
// Compile: gcc -O2 -fopenmp .c -o 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <omp.h>

int i = 0;
int c[5000000] = {0};
int b[5000000] = {0};
int a[5000000] = {0};

int main(int argc, char* argv[]) {
    int t5 = 0;
    int t4 = 0;
    int t3 = 0;

    // CUDA kernel emitted for loop bound=5000000
    // See: .cu
    return 0;
}
