// Generated by BulkCompiler
// Compile: gcc -O2 -fopenmp .c -o 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <omp.h>

int i = 0;
int a[10] = {0};

int main(int argc, char* argv[]) {
    int t6 = 0;
    int t5 = 0;
    int t4 = 0;

    i = 0;

    // auto-parallelised by BulkCompiler
    #pragma omp parallel for schedule(static)
    for (int i = 0; i < 5; ++i) {
        t5 = i * 2;
        a[i] = t5;
    }
    return 0;
}
