// Generated by BulkCompiler
// Compile: gcc -O2 -fopenmp prog.c -o prog

#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

int i = 0;
int c[1000] = {0};
int b[1000] = {0};
int a[1000] = {0};

int main(int argc, char* argv[]) {
    int t5 = 0;
    int t4 = 0;
    int t3 = 0;

    // PARALLEL LOOP — fully parallel, all iterations independent [SIMD/multi-thread safe]
    //   parallel array: c[i]
    i = 0;
L1:;
    t3 = i < 1000;
    if (!(t3)) goto L2;
    t4 = a[i] + b[i];
    c[i] = t4;
    t5 = i + 1;
    i = t5;
    goto L1;
L2:;
    return 0;
}
